### ISSUE TITLE
Removing a person while an account is being reassigned to them answers 500

### ISSUE THREAD

**Issue by chethan123** [chethan123/portfolio#331]
Blocked by: Nothing

## Problem/context

Found in the 2026-09-15 release QA of main 8a2dffb. **PREEXISTING**: it reproduces the same way on baseline 619ff9d (before PRs #323, #326, #330, #328, #329).

Two Settings actions can pass each other's checks when they run at the same moment:

- **Settings → People → Remove** (`POST /settings/people`, `intent=remove`). It checks that the person owns no accounts, then deletes the person.
- **Settings → Accounts → an account → Save** with the owner changed to that same person (`POST /settings/accounts/:id`). It checks that the new owner exists, then updates the account.

Neither check is atomic with its write. Whichever write lands second hits the `account_owner_id_fkey` foreign key, and nothing catches that. The user gets **"Something went wrong"** (HTTP 500), not a message on the form.

## Impact

- Low likelihood: a household of two admins has to click at the same moment. The QA race script hit it on most rounds.
- No data is corrupted, because the foreign key holds and the losing statement rolls back.
- The user still sees a 500 page for an ordinary refusal. That breaks the CLAUDE.md rule that refusals are data (`ValidationError` with a message per field, never a 500). A 500 also tells the user nothing about which action won.

## Exact reproduction

Setup: `docker compose -f compose.test.yaml up -d --wait`, migrate a database, `npm run dev` (app at `http://localhost:5173`), seed with `node --env-file=.env scripts/seed-demo.ts`. Any seeded owner id works as the "other" owner; `1` below.

Save this as `race-remove-person.mjs` in the checkout and run it with `node race-remove-person.mjs`. Set `PSQL` to however you reach the dev database, for example `psql postgres://portfolio:portfolio@127.0.0.1:55432/portfolio -tA`.

```js
// Races "remove person X" against "reassign account A to X", 20 rounds.
import { execSync } from "node:child_process";
const B = process.env.BASE ?? "http://localhost:5173";
const PSQL = process.env.PSQL ?? "psql postgres://portfolio:portfolio@127.0.0.1:55432/portfolio -tA";
const psql = (s) => execSync(PSQL, { input: s }).toString().trim().split("\n")[0];
const post = (path, fields) => fetch(B + path, {
  method: "POST", redirect: "manual",
  headers: { cookie: "masked=0", "content-type": "application/x-www-form-urlencoded" },
  body: new URLSearchParams(fields),
});
const tag = `racec-${Date.now()}`;
const acct = psql(`insert into account (name, institution, kind, owner_id, tax_treatment) values ('${tag}-acct', '', 'bank', 1, 'taxable') returning id;`);
const tally = {};
for (let i = 0; i < 20; i++) {
  const pid = psql(`insert into person (name) values ('${tag}-p${i}') returning id;`);
  psql(`update account set owner_id = 1 where id = ${acct};`);
  const [rm, re] = await Promise.all([
    post("/settings/people", { intent: "remove", personId: pid }),
    post(`/settings/accounts/${acct}`, { name: `${tag}-acct`, institution: "", kind: "bank", ownerId: pid, taxTreatment: "taxable", externalAccountNumber: "" }),
  ]);
  const key = `remove=${rm.status} reassign=${re.status}`;
  tally[key] = (tally[key] ?? 0) + 1;
}
console.log(tally);
```

On a gated instance, send the unlock cookie, or run against an instance with the gate off.

The server log shows `error: insert or update on table "account" violates foreign key constraint "account_owner_id_fkey"` from `updateAccount`, or `update or delete on table "person" violates foreign key constraint "account_owner_id_fkey" on table "account"` from `removePerson`.

## Actual

Across 20 rounds, one of the two POSTs usually answers 500:

- main 8a2dffb, QA run 1: 13/20 rounds had a 500.
- main 8a2dffb, re-run while filing: 19/20 rounds had a 500 (12 from `reassign`, 7 from `remove`).
- baseline 619ff9d: 10/20 rounds had a 500.

## Expected

Neither POST answers 500. Whichever action commits first wins. The other gets a form-level refusal through `ValidationError`, rendered on its own form:

- Remove loses: the existing "`<name>` still owns `<account>`. Change the owner on those accounts first…" message (`app/lib/people.server.ts:162-165`).
- Reassign loses: the existing `ownerId` field message "Choose an owner from the people on this instance." (`app/lib/accounts.server.ts:302`), because the person no longer exists.

## Root cause

Both functions check, then write, with no lock between the check and the write and no translation of the constraint error:

- `removePerson`, `app/lib/people.server.ts:138-169`: reads the person (142-148) and the accounts they own (150-155) on the pool, then runs `deleteFrom("person")` at `:168`. An `updateAccount` that commits between the owned-accounts read and the delete makes the delete violate `account_owner_id_fkey`.
- `updateAccount`, `app/lib/accounts.server.ts:189-253`: `requireOwner` (`:294-304`) reads `person` without a lock, then runs `updateTable("account")` at `:241-252`. A `removePerson` that commits between those steps makes the update violate the same key.
- `app/routes/settings/people.tsx:17-54` and `app/routes/settings/account.tsx:25-52` catch only `ValidationError` and `NotFoundError`, so the `pg` `DatabaseError` (code `23503`) becomes the error boundary's 500.

## Affected files/functions

- `app/lib/people.server.ts`: `removePerson`
- `app/lib/accounts.server.ts`: `updateAccount`, `requireOwner`
- `app/routes/settings/people.tsx`, `app/routes/settings/account.tsx`: shown only for context. They should need no change, because the domain owns the refusal.

## Constraints and non-goals

- The domain owns the refusal. Routes stay thin translators and must not special-case Postgres error codes.
- There are two acceptable fix shapes; pick one and state why:
  1. Serialize: take `for key share` / `for share` on the `person` row in `requireOwner` inside the update's transaction, and lock the person row (`for update`) before counting owned accounts in `removePerson`. Both run in one transaction each.
  2. Translate: catch the foreign-key violation (SQLSTATE `23503`, constraint `account_owner_id_fkey`) in the domain function and rethrow the same `ValidationError` the check would have produced.

  Option 1 is closer to how the repo guards other races (ARCHITECTURE.md §7.2).
- Keep #311 separate. It moves `updateAccount`'s kind guard under `withAccountLock`, and it may land first. If it does, keep the owner lock inside that same transaction rather than adding a second one.
- Changing an owner is not an account-history write, so this does not need `withAccountLock` for its own sake. Do not add a new lock boundary that conflicts with #329's.
- Accounts are never deleted. Removing a person who owns accounts stays refused.
- Not in scope: the malformed person id bigint 500 (#171).

## Acceptance checklist

- [ ] Remove racing a reassignment to the same person never answers 500; the loser gets a `ValidationError`.
- [ ] A remove that loses renders the "still owns …" form message; a reassignment that loses renders the `ownerId` field message.
- [ ] The final state is consistent: either the person is gone and the account keeps its old owner, or the person exists and owns the account.
- [ ] A deterministic regression test covers each ordering (remove first, reassign first).
- [ ] ARCHITECTURE.md §7.2's race table gains a row for this race.

## Verification steps

1. **Write the failing test first**, in `tests/people.test.ts` or a new `tests/person-owner-race.test.ts`. It needs two committed connections, because `withDatabase`'s single rolled-back transaction cannot contend with itself. Copy the shape of `tests/account-lock.test.ts`: `testDatabase()`, `RACE_PREFIX` names and `clearRaces` in `beforeAll`/`afterAll`, `makeFixtures(database)` for `seedPerson`/`seedAccount`, and `backendPid` + `waitUntilBlocked` as the barrier, never a sleep.
   - Ordering A: open transaction 1, run `updateAccount(account.id, { …, ownerId: person.id }, trx1)` without committing. In transaction 2 call `removePerson(person.id, trx2)`, wait until it blocks (after the fix) or skip the barrier (before the fix), then commit 1. Expect `removePerson` to reject with a `ValidationError` whose form message names the account.
   - Ordering B: hold `removePerson` uncommitted in transaction 1, run `updateAccount` to that owner in transaction 2, commit 1. Expect a `ValidationError` on `ownerId`.
   - Before the fix, both orderings surface a `DatabaseError` with code `23503`, or pass their check and violate the key. This is not deterministic without the lock, so the test asserts the `ValidationError` outcome.
   - `removePerson` currently takes `db` as its last parameter, so a transaction can be passed in.
2. Run `node race-remove-person.mjs` from the reproduction above: 0 rounds with a 500.
3. `npm run typecheck`
4. `npm test` (confirm the new tests ran and passed, not skipped)
5. `npm run build`

## Evidence/related

- QA race runs on main: 13/20 and 19/20 rounds with a 500. Baseline 619ff9d: 10/20.
- The same race also sent 3/20 concurrent Set balance requests to 404 on main. That is the #329 owner-change issue filed alongside this one, a separate defect.
- Related: #171 (malformed person id 500), #311 (serialize `updateAccount`'s kind guard with the account lock), #329 (account lock).
